import { useEffect, useState } from 'react'
import { AlertCircle, MessageSquareWarning, Send } from 'lucide-react'
import { toast } from 'sonner'
import { useAuth } from '@/context/AuthContext'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { colors } from '@/theme'

const styles = { open: { color: '#9a6211', background: '#fff4de' }, in_review: { color: '#8a5a2b', background: '#f5e6d3' }, resolved: { color: '#287446', background: '#e7f5ec' } }
export default function ComplaintsPage() {
  const { fetchMyTenancies, fetchComplaints, createComplaint } = useAuth(); const [units, setUnits] = useState([]); const [rows, setRows] = useState([]); const [unitId, setUnitId] = useState(''); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [saving, setSaving] = useState(false)
  const load = async () => { try { const [tenancies, complaints] = await Promise.all([fetchMyTenancies(), fetchComplaints()]); setUnits(tenancies); setRows(complaints.complaints); if (!unitId && tenancies[0]) setUnitId(tenancies[0].unit_id) } catch (e) { toast.error(e.message) } }; useEffect(() => { load() }, [])
  const submit = async (e) => { e.preventDefault(); setSaving(true); try { await createComplaint({ unit_id: unitId, title, description }); toast.success('Complaint lodged. Both you and your landlord have been notified.'); setTitle(''); setDescription(''); load() } catch (error) { toast.error(error.message) } finally { setSaving(false) } }
  return <div className="space-y-5"><div><h1 style={{ fontSize: '1.4rem', fontWeight: 800, color: colors.brown[800] }}>Complaints</h1><p style={{ color: colors.brown[600] }}>Raise a concern and keep a record of the landlord’s response.</p></div><Card><CardHeader><CardTitle style={{ color: colors.brown[800], fontSize: '1rem' }}>Lodge a complaint</CardTitle><CardDescription>Your landlord will receive an email notification immediately.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={submit}><div><Label>Unit</Label><Select value={unitId} onValueChange={setUnitId} items={units.map((u) => ({ value: u.unit_id, label: `${u.building_name} · Unit ${u.unit_number}` }))}><SelectTrigger className="w-full"><SelectValue placeholder="Select a unit" /></SelectTrigger><SelectContent>{units.map((u) => <SelectItem key={u.unit_id} value={u.unit_id}>{u.building_name} · Unit {u.unit_number}</SelectItem>)}</SelectContent></Select></div><div><Label>Subject</Label><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="What is your concern?" maxLength={150} /></div><div><Label>Details</Label><Textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Explain the concern clearly…" rows={4} maxLength={2000} /></div><Button type="submit" disabled={saving || !unitId || !title.trim() || !description.trim()} className="bg-[#a0622a] text-white hover:bg-[#8a5424]"><Send size={15} /> {saving ? 'Submitting…' : 'Lodge complaint'}</Button></form></CardContent></Card><div><h2 className="mb-3" style={{ fontWeight: 800, color: colors.brown[800] }}>Your complaints</h2><div className="grid gap-4 md:grid-cols-2">{rows.length === 0 ? <Card><CardContent className="flex items-center gap-2 py-8" style={{ color: colors.brown[600] }}><MessageSquareWarning size={18} color={colors.accent} /> No complaints lodged yet.</CardContent></Card> : rows.map((row) => <Card key={row.id}><CardContent className="space-y-3 p-5"><div className="flex items-start justify-between gap-2"><div><p style={{ fontWeight: 800, color: colors.brown[800] }}>{row.title}</p><p className="text-sm" style={{ color: colors.brown[600] }}>{row.building_name} · Unit {row.unit_number}</p></div><Badge style={styles[row.status]}>{row.status.replace('_', ' ')}</Badge></div><p className="text-sm" style={{ color: colors.brown[700] }}>{row.description}</p><p className="text-xs" style={{ color: colors.brown[600] }}>Submitted {new Date(row.created_at).toLocaleDateString('en-KE')}</p></CardContent></Card>)}</div></div></div>
}
