import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { useAuth } from '@/context/AuthContext'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { colors } from '@/theme'
const styles = { open: { color: '#9a6211', background: '#fff4de' }, in_review: { color: '#8a5a2b', background: '#f5e6d3' }, resolved: { color: '#287446', background: '#e7f5ec' } }
export default function ComplaintsPage() { const { fetchComplaints, updateComplaint } = useAuth(); const [rows, setRows] = useState([]); const load = () => fetchComplaints().then((r) => setRows(r.complaints)).catch((e) => toast.error(e.message)); useEffect(() => { load() }, [])
  return <div className="space-y-5"><div><h1 style={{ fontSize: '1.4rem', fontWeight: 800, color: colors.brown[800] }}>Complaints</h1><p style={{ color: colors.brown[600] }}>Review tenant concerns and keep residents informed.</p></div><div className="grid gap-4 md:grid-cols-2">{rows.length === 0 ? <Card><CardContent className="py-10 text-center" style={{ color: colors.brown[600] }}>No complaints received.</CardContent></Card> : rows.map((row) => <Card key={row.id}><CardContent className="space-y-4 p-5"><div className="flex items-start justify-between gap-3"><div><p style={{ fontWeight: 800, color: colors.brown[800] }}>{row.title}</p><p className="text-sm" style={{ color: colors.brown[600] }}>{row.raised_by} · {row.building_name} · Unit {row.unit_number}</p></div><Badge style={styles[row.status]}>{row.status.replace('_', ' ')}</Badge></div><p className="text-sm" style={{ color: colors.brown[700] }}>{row.description}</p><Select value={row.status} onValueChange={async (status) => { try { await updateComplaint(row.id, { status }); toast.success('Complaint updated and tenant notified.'); load() } catch (e) { toast.error(e.message) } }} items={[{ value: 'open', label: 'Open' }, { value: 'in_review', label: 'In review' }, { value: 'resolved', label: 'Resolved' }]}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="open">Open</SelectItem><SelectItem value="in_review">In review</SelectItem><SelectItem value="resolved">Resolved</SelectItem></SelectContent></Select></CardContent></Card>)}</div></div>
}
